readme updates
tgpethan/Revolution pull request #9
Opened 2020-01-02 23:33 UTC by the-basic-geek

2020-01-02 23:39 UTC, tgpholly requested changes
Maybe add more before requesting a review?

2020-01-03 04:28 UTC, tgpholly requested changes
It's mostly ok, just keep it the same as the mockup and place it in codeblocks.

2020-01-03 04:28 UTC, tgpethan commented on README.md
> +<p align="left">git clone https://github.com/tgpethan/Revolution.git then, cd Revolution. run npm i, then run node .
Keep the instructions as original and place inside codeblocks to keep formatting correct

2020-01-03 04:28 UTC, tgpethan commented on README.md
> +<p align="left">Download latest build (https://github.com/tgpethan/Revolution/releases/latest) then Unzip the zip and Run revolution executable
Keep the instructions as original and place inside codeblocks to keep formatting correct

2020-01-03 04:43 UTC, tgpholly reviewed
Weird It'll do. I'll add some final stuff and i'll approve it

2020-01-03 04:44 UTC, the-basic-geek commented
oki

2020-01-03 04:58 UTC, tgpholly approved these changes

2020-01-03 04:59 UTC, merged